In [3]:
import numpy as np
def conv(A_prev, stride, f, b, W):
    Z = np.zeros([1, 2, 2, 3])
    m, n_H, n_W, n_C = Z.shape
    for batch in range(m):
        # batch size 
        for he in range(n_H):
            # height
            for wi in range(n_W):
                # width
                for ch in range(n_C):
                    # Channels
                    mid_A_prev = A_prev[batch, he * stride: he * stride + f, wi * stride: wi * stride + f, :]
                    Z[batch, he, wi, ch] = np.sum(mid_A_prev * W[:, :, ch].reshape(1, f, f, 1)) + b[:, :, :, ch]
    return Z


In [6]:
import numpy as np
A_prev = np.array([
    [
    [
       [1], [2], [3]
    ],
    [
       [3], [2], [1]
    ],
    [
        [3], [1], [3]
    ]
    ]
])

W = np.array(
    [[
        [
            1, 3, 1
        ],
        [
            2, 1, 2
        ]
    ],
    [
        [
            1, 3, 3
        ],
        [
            3, 1, 3
        ]
    ]]
)

b = np.array([
    [
        [
            [1, 2, 3]
        ]
    ]
])
print(A_prev.shape, W.shape, b.shape)
Z = conv(A_prev=A_prev, stride=1, f=2, b=b, W=W)
print(Z)
print(Z.shape)
print(Z.sum(axis=0).sum(axis=0).sum(axis=0).sum(axis=0))

(1, 3, 3, 1) (2, 2, 3) (1, 1, 1, 3)
[[[[15. 18. 23.]
   [14. 18. 20.]]

  [[14. 23. 22.]
   [15. 15. 19.]]]]
(1, 2, 2, 3)
216.0


C:\Users\Mengkang Li\AppData\Local\Temp\ipykernel_26524\2652777040.py:14: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  Z[batch, he, wi, ch] = np.sum(mid_A_prev * W[:, :, ch].reshape(1, f, f, 1)) + b[:, :, :, ch]


In [20]:
print(W[:, :, 0])
print(A_prev[0, 0: 2, 0: 2, 0])

[[1 2]
 [1 3]]
[[1 2]
 [3 2]]


In [21]:
def pool_forward(A_prev, f, stride):
    """
    Inputs:
    - A_prev: The activation output from the previous layer, with dimension of (m, n_H_prev, n_W_prev, n_C_prev)
    - (1) m is the batch size (2) n_H_prev is the height of previous output
    - (3) n_W_prev is the width of the previous output (4) n_C_prev is the number of channels from the previous output

    - f: Integer, the height and width of the pooling windows
    - stride: Integer, indicate how far the pooling move each time

    Outputs:
    - A: The output of the pooling layers, with dimension of (m, n_H, n_W, n_C)
    - A_prev, f, stride, n_H, n_W, n_C

    """
    (m, n_H_prev, n_W_prev, n_C_prev) = A_prev.shape

    #####################################################################################
    # TODO: Compute the height and weight of the output after convolution  #
    # Replace None with your formula                       #
    #####################################################################################
    n_H = int (np.ceil((n_H_prev - f) / stride + 1))
    n_W = int (np.ceil((n_W_prev - f) / stride + 1))
    n_C = n_C_prev

    # initialize the output
    A = np.zeros((m, n_H, n_W, n_C))
    #####################################################################################
    # TODO: Implement the Pooling process                     #
    # Hint: You can use a for loop to iterate all samples, H, W, C    #
    #####################################################################################

    for batch in range(m):
        for he in range(n_H):
            for wi in range(n_W):
                for ch in range(n_C):
                    A[batch][he][wi][ch] = np.max(A_prev[batch, stride * he: stride * he + f, stride * wi: stride * wi + f, ch])

    #####################################################################################
    #             End of Your Code                   #
    #####################################################################################

    assert(A.shape == (m, n_H, n_W, n_C))


    return A, A_prev, f, stride, n_H, n_W, n_C

In [31]:
p_test = np.array(
    [
        [
            [
            [2, 4, 5],
            [3, 6, 7],
            [1, 3, 2]
            ],
            [
            [1, 3, 2],
            [2, 4, 5],
            [3, 6, 7]
            ],
            [
            [3, 6, 7],
            [1, 3, 2],
            [2, 4, 5]
            ]
        ]
    ]
)
print(p_test.shape)
pool_result = pool_forward(p_test, 2, 2)
print(p_test[0, 2: 4, 2: 4, 2])
print(pool_result[0])

(1, 3, 3, 3)
[[5]]
[[[[3. 6. 7.]
   [3. 6. 7.]]

  [[3. 6. 7.]
   [2. 4. 5.]]]]


In [1]:
for i in range(0, 4, 2):
    print(i)

0
2


In [3]:
import numpy as np
A = np.array([[1, 2, 3],
     [4, 5, 6]])
print(A.shape)
print(np.sum(A, axis=1))

(2, 3)
[ 6 15]
